### PR TITLE
initial setup for @jeremylweiss

### PR DESCRIPTION
**Pull request by jeremylweiss**
Got through the checklist, and think all is in order, although not sure about the Github Actions check

### CODE REVIEW

**Comment by Aariq** [comment]
I'm slightly afraid to merge this because the PR seems to think a **_bunch_** of files are empty, not just that yaml file.  It's weird though, because they're all there when I pull the branch down or when you just browse the files on that branch on GitHub.  Seems like it's _maybe_ related to file permissions changes (https://github.com/orgs/community/discussions/6814). 

I'll merge and deal with the consequences, if any.

**Comment by jeremylweiss** [comment]
Apologies, I should have noted that by deleting my initial local clone and redoing the cloning process via SSH instead of HTTPS solved the problems of the blank .yaml file and the long list of commits, only 2/3 of which I could actually commit and push (if I had taken that step). If the GitHub Actions check passes, I think we should be good to go

**Comment by Aariq** [comment]
I can confirm that the github action is working now because I succeeded in breaking the app by merging a PR 🤦‍♂️

**Comment by jeremylweiss** [comment]
Please let me know if I can help somehow. I haven't pulled the latest `main`, so still have the version that worked yesterday. I noticed this AM that the Shiny app for the AZMet qa-qc dashboard under my Connect login is not working anymore

**Pull request merged**
